hms/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hmsapp.urls')),
]

hmsapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.
class UserProfile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    city=models.CharField(max_length=10)
    gender=models.CharField(max_length=10)
    role = models.CharField(max_length=10,default='patient')
    birth_date = models.DateField(null=True, blank=True)
    history_completed = models.BooleanField(default=False)
    def __str__(self):
        return "{0} {1}" .format(self.user.first_name,self.user.last_name)    
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    instance.userprofile.save()

class UserHistory(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    diabetes = models.CharField(max_length = 100)
    blood_pressure = models.CharField(max_length = 100)
    heart_problems = models.CharField(max_length = 100)
    drink = models.CharField(max_length = 100)
    smoke = models.CharField(max_length = 100)
    drugs = models.CharField(max_length = 100)
    def __str__(self):
        return "{0} {1}" .format(self.user.first_name,self.user.last_name)

class Case(models.Model):
    user = models.ForeignKey(User,default=1,on_delete=models.CASCADE)
    symptoms=models.CharField(max_length=60)
    disease=models.CharField(max_length=30, blank = True)
    starting_date=models.DateField(auto_now= True)
    last_visit=models.DateField(blank = True, null = True)
    def __str__(self):
        return str(self.user.first_name)+"\t"+str(self.last_visit)

class Visits(models.Model):
    case = models.ForeignKey(Case,default=1,on_delete=models.CASCADE)
    progress = models.CharField(max_length=50,blank=True)
    date = models.DateField(auto_now = True)
    temperature = models.IntegerField(blank = True, null  = True)
    bp = models.CharField(max_length = 6, blank = True)
    current_status = models.CharField(max_length=60)
    disease = models.CharField(max_length=30,blank=True)
    time = models.TimeField(default = "00:00")
    def __str__(self):
        return str(self.case_id)

class Medic(models.Model):
    visit=models.ForeignKey(Visits,on_delete=models.CASCADE)
    medicines=models.TextField(max_length=100)
    price=models.TextField(max_length=10)
    def __str__(self):
        return self.medicines

class Labs(models.Model):
    visit=models.ForeignKey(Visits,on_delete=models.CASCADE)
    test=models.TextField(max_length=50)
    price=models.TextField(max_length=10)
    def __str__(self):
        return self.test
    
class Current(models.Model):
    cmedic=models.IntegerField()
    clab=models.IntegerField()
    cdoc = models.IntegerField(default = 1)
    cvisit = models.IntegerField(default = 1)
    

hmsapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import UserHistory,Case,Visits
CHOICES= [
    ('male', 'Male'),
    ('female', 'Female'),
    ('other', 'Other'),
    
    ]

class UserLoginForm(forms.Form):
     username=forms.CharField(max_length=20,label='Phone Number')
     password=forms.CharField(max_length=100,widget=forms.PasswordInput)
      
           

class SignUpForm(UserCreationForm):
    
    gender=forms.CharField(max_length=10,label='gender', widget=forms.RadioSelect(choices=CHOICES))
    city=forms.CharField(max_length=10)
    birth_date = forms.DateField(help_text='Required. Format: YYYY-MM-DD')
    email =forms.EmailField(required=True)
    first_name=forms.CharField(max_length=20)
    last_name=forms.CharField(max_length=20)
    class Meta:
        model = User
        fields = ['first_name','last_name','username','birth_date', 'password1', 'password2','gender','city','email' ]


class HistoryForm(forms.ModelForm):
    choices1 = [
    ('Never', 'Never'),
    ('Once an year', 'Once an year'),
    ('Few times a year', 'Few times a year'),
    ('Few times a month', 'Few times a month'),
    ('Few times a week', 'Few times a week'),
    ('Daily', 'daily'),
    ('Many times a day', 'Many times a day'),    
    ]
    choices2 = [
    ('Yes', 'Yes'),
    ('No', 'No'),
    ]
    diabetes=forms.CharField(max_length=100,label='Do you have Diabetes?', widget=forms.RadioSelect(choices=choices2))
    blood_pressure=forms.CharField(max_length=100,label='Do you have Blood Pressure Problems?', widget=forms.RadioSelect(choices=choices2))
    heart_problems=forms.CharField(max_length=100,label='Do you have have Heart Problems?', widget=forms.RadioSelect(choices=choices2))
    drink=forms.CharField(max_length=100,label='How often do you have alcohol?', widget=forms.RadioSelect(choices=choices1))
    smoke=forms.CharField(max_length=100,label='How often do you smoke?', widget=forms.RadioSelect(choices=choices1))
    drugs=forms.CharField(max_length=100,label='How often do you have drugs?', widget=forms.RadioSelect(choices=choices1))
    class Meta:
        model = UserHistory
        fields = ["diabetes",
        "blood_pressure",
        "heart_problems",
        "drink",
        "smoke",
        "drugs",]

class CreateCase(ModelForm):
    class Meta:
        model = Case
        fields = ['symptoms',]

class CreateVisit(ModelForm):
    class Meta:
        model = Visits
        fields = ["current_status","time"]

templates/createcase.html
{% extends 'home.html' %}

{% block head %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% load static %}
<link href = {% static "medic_lab.css" %} rel = "stylesheet" type = "text/css">
<title> Case form </title>
{% endblock %}

{% block body %}
<body  background={% static "gradient.jpg" %} >
        <div class="container" style="padding-top: 40px; background-color: white;" >
    
        <form method="POST" class="container">
                {% csrf_token %}
                <div class="container register-form" style = "margin-top: 20px;">
                    <div class="form">
                        <div class="note">
                            <p style = "font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; font-size: 30px;">Create Your Case</p>
                        </div>
                
                        <div class="form-content">
                            <div class="row">
                                <div class="col-md-12">
                                        <p><label style="font-family: Verdana, Geneva, Tahoma, sans-serif;" for="id_symptoms">Symptoms:</label> <input class="form-control" type="text" name="symptoms" maxlength="60" required id="id_symptoms"></p>
                                        <label style="font-family: Verdana, Geneva, Tahoma, sans-serif;" for = "time">Time for appointment:</label> 
                                        <input class="form-control" type = "text", name = "time" id = "time"><br>
                                </div>
                            </div><br><br>
                            <center>
                                    <a class="btn btnSubmit" href="/" role="button">Back</a>
                                    <input class="btnSubmit" type="submit" value="Submit">
                                    
                                
                            </center>
                        </div>
                    </div>
                </div>
    </form>
    </div>
    





    {% endblock %}

templates/createvisit.html
{% extends 'home.html' %}

{% block head %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% load static %}
<link href = {% static "medic_lab.css" %} rel = "stylesheet" type = "text/css">
<title> Visit form </title>
{% endblock %}

{% block body %}
<body  background={% static "gradient.jpg" %} >
<div class="container" style="padding-top: 40px; background-color: white;" >
    
    <form method="POST" class="container">
        {% csrf_token %}
            <div class="container register-form" style = "margin-top: 20px;">
                <div class="form">
                    <div class="note">
                        <p style = "font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; font-size: 30px;">Create Your Visit</p>
                    </div>
            
                    <div class="form-content">
                        <div class="row">
                            <div class="col-md-12">
                                <p><label for="id_current_status" style="font-family: Verdana, Geneva, Tahoma, sans-serif;">Current status:</label> <input type="text" class="form-control" name="current_status" maxlength="60" required id="id_current_status"></p>
<p><label for="id_time" style="font-family: Verdana, Geneva, Tahoma, sans-serif;">Time:</label> <input class="form-control" id = "datetimepicker3" type="text" name="time" value="00:00" required></p>
    
    <label for="exampleFormControlSelect1" style="font-family: Verdana, Geneva, Tahoma, sans-serif;">Existing cases:</label>
    <select class="form-control" id="exampleFormControlSelect1" name="dropdown1">
         {% for case in cases %}
          <option value="{{ case.id }}">
                {{ case.symptoms }}
                {{ case.starting_date }}
          </option>
          {% endfor %}
          
        </select>
                            </div>
                        </div><br><br>
                        <center>
                                <a class="btn btnSubmit" href="/" role="button">Back</a>
                            <input class="btnSubmit" type="submit" value="Submit">
                        </center>
                    </div>
                </div>
            </div>
</form>
</div>

{% endblock %}

templates/doctorhome.html
{% extends "home.html" %}

{% block head %}
{% load static %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<script src={% static "doctor.js" %}></script>
<title>Doctor Home</title>
<link href = {% static "medic_lab.css" %} rel = "stylesheet" type = "text/css">
<link href = {% static "doctor.css" %} rel = "stylesheet" type = "text/css">
{% endblock %}

{% block body %}
<body  background={% static "gradient.jpg" %} >
    
<div class="container" style="margin-top:0px;">
    <div class="row">
        <div class="col-lg-12 my-3">
            <div class="pull-right">
                
            </div>
        </div>
    </div> 
    <div id="products" class="row view-group" style="margin-bottom: 0px;" >
                <div class="item col-xs-6 col-lg-6" >
                    <div class="thumbnail card" style="border-radius: 20px;">
                        
                        <div class="caption card-body" style="margin-bottom: 8px;">
                            <center><h4 class="group card-title inner list-group-item-heading">
                                Patient Information</h4></center><br>
                                <label style="font-family: Verdana, Geneva, Tahoma, sans-serif; font-size: 20px; float: left;" >Patient Name:</label><span style="display: block; overflow: hidden;padding: 0 4px 0 6px"><input class="form-control" value=" {{ patient.first_name }} {{ patient.last_name }}" style="width: 100%; text-transform: capitalize; border-radius: 20px;" disabled></span><br>
                                <label style="font-family: Verdana, Geneva, Tahoma, sans-serif; font-size: 20px; float: left;" >Date of Birth:</label><span style="display: block; overflow: hidden;padding: 0 4px 0 6px"><input class="form-control" value=" {{ profile.birth_date }}" style="width: 100%; text-transform: capitalize; border-radius: 20px;" disabled></span><br>
                                <label style="font-family: Verdana, Geneva, Tahoma, sans-serif; font-size: 20px; float: left;" >Diabetes:</label><span style="display: block; overflow: hidden;padding: 0 4px 0 6px"><input class="form-control" value="{{ history.diabetes }}" style="width: 100%; text-transform: capitalize; border-radius: 20px;" disabled></span><br>
                                <label style="font-family: Verdana, Geneva, Tahoma, sans-serif; font-size: 20px; float: left;" >Blood Problems:</label><span style="display: block; overflow: hidden;padding: 0 4px 0 6px"><input class="form-control" value=" {{ history.blood_pressure }}" style="width: 100%; text-transform: capitalize; border-radius: 20px;" disabled></span><br>
                                <label style="font-family: Verdana, Geneva, Tahoma, sans-serif; font-size: 20px; float: left;" >Heart Problems:</label><span style="display: block; overflow: hidden;padding: 0 4px 0 6px"><input class="form-control" value=" {{ history.heart_problems }}" style="width: 100%; text-transform: capitalize; border-radius: 20px;" disabled></span><br>
                                <label style="font-family: Verdana, Geneva, Tahoma, sans-serif; font-size: 20px; float: left;" >Drink:</label><span style="display: block; overflow: hidden;padding: 0 4px 0 6px"><input class="form-control" value=" {{ history.drink }}" style="width: 100%; text-transform: capitalize; border-radius: 20px;" disabled></span><br>
                                <label style="font-family: Verdana, Geneva, Tahoma, sans-serif; font-size: 20px; float: left;" >Smoke:</label><span style="display: block; overflow: hidden;padding: 0 4px 0 6px"><input class="form-control" value="  {{ history.smoke }}" style="width: 100%; text-transform: capitalize; border-radius: 20px;" disabled></span><br>
                                <label style="font-family: Verdana, Geneva, Tahoma, sans-serif; font-size: 20px; float: left;" >Drugs:</label><span style="display: block; overflow: hidden;padding: 0 4px 0 6px"><input class="form-control" value=" {{ history.drugs }}" style="width: 100%; text-transform: capitalize; border-radius: 20px;" disabled></span><br>
 </div>
                    </div>
                </div>
                
                <div class="item col-xs-6 col-lg-6">
                    <div class="thumbnail card" style="border-radius: 20px; padding-bottom: 0px;" >
                        <div class="caption card-body">
                            <label style="font-family: Verdana, Geneva, Tahoma, sans-serif; font-size: 20px; float: left;" >Symptoms:</label><span style="display: block; overflow: hidden;padding: 0 4px 0 6px"><input class="form-control" value=" {{ visit.current_status }}" style="width: 100%; text-transform: capitalize; border-radius: 20px;" disabled></span><br>
                            <label style="font-family: Verdana, Geneva, Tahoma, sans-serif; font-size: 20px; float: left;" >Temperature:</label><span style="display: block; overflow: hidden;padding: 0 4px 0 6px"><input class="form-control" value=" {{ visit.temperature }}" style="width: 100%; text-transform: capitalize; border-radius: 20px;" disabled></span><br>
                            <label style="font-family: Verdana, Geneva, Tahoma, sans-serif; font-size: 20px; float: left;" >Blood Pressure:</label><span style="display: block; overflow: hidden;padding: 0 4px 0 6px"><input class="form-control" value=" {{ visit.bp }}" style="width: 100%; text-transform: capitalize; border-radius: 20px;" disabled></span><br>
                            <label for="exampleFormControlSelect1" style="font-family: Verdana, Geneva, Tahoma, sans-serif; font-size: 20px; float: left;">Existing Visits:</label>
   <span style="display: block; overflow: hidden;padding: 0 4px 0 6px;" > <form method="POST" action="visitinfo">
    <form action="visitinfo" method="POST">   
    {% csrf_token %}
    <select class="form-control" style="border-radius: 20px;" id="exampleFormControlSelect1" name="dropdown2">
         {% for visit in visits_of_case %}
          <option value="{{ visit.id }}">
                {{ visit.date }}
          </option>
          {% endfor %}</select></span><center><input type="submit" value="Submit" class="btnSubmit" style=" padding: 5px 20px 5px 9px;  margin:5px 0px ; margin-bottom: 0px;"></center>
        </form> </div>
                                <form method="POST" action="save_doc">
                                    {% csrf_token %}<div class="form-group" style="margin-left: 20px; margin-right: 20px; margin-bottom: 0px; ">
                                    <label for="exampleFormControlTextarea1" style="font-family: Verdana, Geneva, Tahoma, sans-serif; font-size: 20px; float: left;" >Disease:</label><span style=" display: block; overflow: hidden;padding: 0 4px 0 6px"><input class="form-control" type="text" name="disease" style="width: 100%; border-radius: 20px;" ></span><br>
                                    <label for="exampleFormControlTextarea1" style="font-family: Verdana, Geneva, Tahoma, sans-serif; font-size: 20px; float: left;" >Progress:</label><span style=" display: block; overflow: hidden;padding: 0 4px 0 6px"><input class="form-control" type="text" name="progress" style="width: 100%; border-radius: 20px;" ></span><br>
                                    
                                    <label for="exampleFormControlTextarea1" style="font-family: Verdana, Geneva, Tahoma, sans-serif; font-size: 20px; float: left;" >Medicine:</label><span style="display: block; overflow: hidden;padding: 0 4px 0 6px"><textarea id="exampleFormControlTextarea1" class="form-control" type="text" rows="2" name="medicines" style="width: 100%; border-radius: 20px;" ></textarea></span><br>
                                    </div>
                              
                              <div class="form-group" style="margin-left: 20px; margin-bottom: 11px; margin-right: 20px;">
                                    <label for="exampleFormControlTextarea1" style="font-family: Verdana, Geneva, Tahoma, sans-serif; font-size: 20px; float: left;" >Test:</label><span style="display: block; overflow: hidden;padding: 0 4px 0 6px"><textarea id="exampleFormControlTextarea1"  class="form-control" type="text" rows="2" name="test" style="width: 100%; border-radius: 20px;" ></textarea></span><br>
                                  
                              </div>
                        </div>
                    </div>
                
                
               
            </div>
                        <center>
            <input type="submit" class="btnSubmit" style="padding:10px 40px 10px 40px; margin:0px 10px;" value="Save">
            <a href="/logout" class="btn btnSubmit" style="padding:10px 40px 10px 40px; margin:0px 10px;;">Logout</a>
          </center>
</form>

  
</div>


{% endblock %}

templates/except.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Exception Page</title>
        {% load static %}
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href = {% static "medic_lab.css" %} rel = "stylesheet" type = "text/css">
        </head>

        <body  background={% static "gradient.jpg" %} >
                <div class="container" style="padding-top: 40px; background-color: white;" >
                    
                    
                            <div class="container register-form" style = "margin-top: 20px;">
                                <div class="form">
                                    <div class="note">
                                        <p style = "font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; font-size: 30px;">Exception Message</p>
                                    </div>
                            
                                    <div class="form-content">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <p><label for="id_current_status" style="font-family: Verdana, Geneva, Tahoma, sans-serif; font-size: 25px; text-align: center;">We have reached the last patient till now. Sit back and relax for a while.</label></p>
                
                                            </div>
                                        </div><br><br>
                                        <center>
                                            <a class="btn btnSubmit" style="font-size:25px; width:20%;" href="/" role="button">Recheck</a>
                                            <a class="btn btnSubmit" style="font-size:25px; width:20%;" href="/logout" role="button">Logout</a>
                                            
                                        </center>
                                    </div>
                                </div>
                            </div>
                
                </div>







</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    {% block head %}
    <title>homepage</title>
    {% endblock %}
</head>
<body>
    {% block body %}
    <h2 class="continer">Wrong Template</h2>
    {% endblock %}
</body>
</html>

templates/signup.html
{% extends 'home.html' %}

{% block head %}
{% load static %}
<link href={% static "signup.css" %} type="text/css" rel="stylesheet">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<title> registration form</title>

<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker3.css" rel="stylesheet" id="bootstrap-css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"></script>
<script>$('.datepicker').pickadate();</script>
<script src={% static "signup.js" %}></script>
{% endblock %}

{% block body %}
{% for message in messages %}

                    <div class="alert alert-success">
                        <a class="close" href="#" data-dismiss="alert">×</a>

                        {{ message }}

                    </div>
            {% endfor %}
<div class="container register">
        <form method="POST" class="container" >

                {% csrf_token %}
    <div class="row">
        <div class="col-md-3 register-left">
            <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt=""/>
            <h3>Welcome</h3>
            <p>You are 30 seconds away from good health!</p>
            <a href="/login" class="btn btn-primary">Already have an Account?</a>
        </div>
        <div class="col-md-9 register-right">
            
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <h3 class="register-heading">Patient Registration</h3>
                    <div class="row register-form">
                        <div class="col-md-6">
                                <div class="form-group">
                                        <input type="text" class="form-control" placeholder="First Name *"  name="first_name" maxlength="20" required id="id_first_name" value="">
                                    </div>
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Last Name *" value="" name="last_name" maxlength="20" required id="id_last_name">
                                        
                                    </div>
                                    <div class="form-group">
                                        <input type="password" name="password1" required id="id_password1" class="form-control" placeholder="Password *" value="">
                                    
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control" name="password2" required id="id_password2" placeholder="Confirm Password *" value="">
                                        
                                    </div>
                                    <div class="form-group">
                                        <div class="maxl">
                                            <label class="radio inline"> 
                                                <input type="radio" name="gender" value="male" maxlength="10" required id="id_gender_0" checked>
                                                <span> Male </span> 
                                            </label>
                                            <label class="radio inline"> 
                                                <input type="radio" name="gender" value="female" maxlength="10" required id="id_gender_1">
                                                <span>Female </span> 
                                            </label>
                                            <label class="radio inline"> 
                                                    <input type="radio" name="gender" value="other" maxlength="10" required id="id_gender_2">
                                                    <span> Others </span> 
                                                </label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <input type="email" class="form-control" name="email" required id="id_email" placeholder="Your Email *" value="" >
                                        
                                    </div>
                                    <div class="form-group">
                                        <input type="tel" pattern="[0-9]{10}" name="username" maxlength="150" autofocus required id="id_username" class="form-control" placeholder="Your Phone *" value="" >
                                        
                                    </div>
                                    <div class="form-group">
                                            
                                                    
                                                                
                                                                    
                                                                            <div class='input-group date' id='datepicker'>
                                                                                    <input type="text" class="form-control" placeholder="Birth date *" value="" name="birth_date" required id="id_birth_date">
                                                                                <span class="input-group-addon">
                                                                                    <span class="glyphicon glyphicon-calendar"></span>
                                                                                </span>
                                                                            </div>
                                                                       
                                                        
                                                        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"></script>
                                                        <script >
                                                            $(function () {
                                                                $('#datepicker').datepicker({
                                                                    format: "yyyy-mm-dd",
                                                                    autoclose: true,
                                                                    todayHighlight: true,
                                                                    showOtherMonths: true,
                                                                    selectOtherMonths: true,
                                                                    autoclose: true,
                                                                    changeMonth: true,
                                                                    changeYear: true,
                                                                    orientation: "button"
                                                                });
                                                            });
                                                        </script>
                                                  
                                               
                                            <!-- <input type="text" class="form-control" placeholder="Birth date *" value="" name="birth_date" required id="id_birth_date"> -->
                                    </div>
                                    <div class="form-group">
                                        <input type="text" class="form-control" name="city" maxlength="10" required id="id_city" placeholder="Enter Your City *" value="" >
                            
                                    </div>
                                    <input type="submit" class="btnRegister"  value="Submit">
                                </div>
                    </div>
                </div>


<script type="text/javascript">
$('.datepicker').pickadate();
</script>

{% endblock %}